### ISSUE TITLE
StakeDistribution multiply dangling stake incorrectly

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/chain-libs#190]
version: newest master

method: `assign_account_value` in `stake/distribution.rs` file. If we have a DelegationType::Ratio which delegates e.g.  Value(100) to non existing 4 pool stakes it is expected that StakeDistribution struct will hold dangling value equal to 100, however it is equal to `800` (this is due to the face that 
 `assign_account_value` mutliply incoming value by 2 and does it 4 times (4 is the number of pools)).

Please run test: `dangling_stake_multiplied` in `stake/distribution.rs` to observe mentioned behavior (it is possible to uncomment commented assertion to get proper expected value).

**Comment by vincenthz** [comment]
I think this got fixed yesterday already, there was a assignment / copy that ran amok
