### ISSUE TITLE
chain-storage-sqlite: Add consistency checks

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/chain-libs#276]
The current storage implementation has issues with consistency, including:

- It is possible to put a block while its parent is not present in the database.
- ~~It is possible to put a tag on a non-existent header~~.

Consider adding checks to the database queries to prevent inconsistency in an atomic way.

**Comment by eugene-babichenko** [comment]
The 2nd is not possible.
https://github.com/input-output-hk/chain-libs/blob/master/chain-storage-sqlite-old/src/lib.rs#L64

**Comment by mzabaluev** [comment]
> The 2nd is not possible.
> https://github.com/input-output-hk/chain-libs/blob/master/chain-storage-sqlite-old/src/lib.rs#L64

That's the spirit. We should put the constraint on the parent field in the `BlockInfo` table (why is this separate from `Blocks` BTW?).

**Comment by eugene-babichenko** [comment]
All of these are fixed and we are not using sqlite anymore.
