### ISSUE TITLE
Update rusqlite to 0.21, consolidate chain-storage-sqlite crates

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/chain-libs#288]
The `rusqlite` version we use is quite old and has some problems for Windows builds: @danielSanchezQ reported it prevents fixing https://github.com/input-output-hk/jormungandr/issues/1699, while my standalone experiment with 0.21 and "bundled" worked well with `crt-static`.

Update the `rusqlite` dependency to the latest version (keep "bundled" on or optionally-default for the time being). There is a use of `r2d2_sqlite` backend in `chain-storage-sqlite`, which is ironically the more outdated crate, so that needs to be dropped and `chain-storage-sqlite-old` renamed as the only surviving storage implementation.

**Comment by eugene-babichenko** [comment]
Done in #297.
