### ISSUE TITLE
PubKeyTag throws an error for ADA redeemed to a Byron address

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/chain-libs#450]
# Problem description

Consider this address `Ae2tdPwUPEZ3MHKkpT5Bpj549vrRH7nBqYjNXnCV8G2Bc2YxNcGHEa8ykDp` that appears on chain: https://explorer.cardano.org/en/address?address=Ae2tdPwUPEZ3MHKkpT5Bpj549vrRH7nBqYjNXnCV8G2Bc2YxNcGHEa8ykDp

If you try and parse it using `ExtendedAddr::from_str(s)` it will throw `encoding error`.

Notably, deserialization will work up until it tries to parse the `PubKeyTag` here: https://github.com/input-output-hk/chain-libs/blob/1c7829f9b297b95a8a4982b2811035b729556637/cardano-legacy-address/src/address.rs#L364

Specifically, it will fail on this line https://github.com/input-output-hk/chain-libs/blob/1c7829f9b297b95a8a4982b2811035b729556637/cardano-legacy-address/src/address.rs#L41 because `reader.unsigned_integer()` returns `2`

# Explanation for why this is suddenly a problem

As you can see, the old Rust library for Cardano didn't have this issue: https://github.com/input-output-hk/chain-libs/blob/1c7829f9b297b95a8a4982b2811035b729556637/cardano-legacy-address/src/address.rs#L364

This is because instead of forcing the `PubKeyTag` to be 0, it instead allowed for

```
fn from_u64(v: u64) -> Option<Self> {
        match v {
            0 => Some(AddrType::ATPubKey),
            1 => Some(AddrType::ATScript),
            2 => Some(AddrType::ATRedeem),
            _ => None,
        }
    }
}
```

Presumably this was removed because it wasn't required by Jormungandr. You can see the original commit that adds legacy address support to this codebase already had script & redemption addresses removed https://github.com/input-output-hk/chain-libs/commit/3e07f8f247d2510f65d4c72acd56741dc8a33c1d#diff-1df297c6506c90a84eeb3b61df2dd4b1

**Comment by vincenthz** [comment]
cardano-legacy-address is not about supporting all addresses types from byron, it's about having the ability to lift a select set of byron data (utxo with pubkey address) for jormungandr. There's no reason to add redeem addresses, since we have no way to redeem them.

For full compatibility, I suggest [rust-cardano address](https://github.com/input-output-hk/rust-cardano/blob/master/cardano/src/address.rs)
