### ISSUE TITLE
Merging build errors to master

### ISSUE THREAD

**Issue by hosekhoshtaghaza** [input-output-hk/chain-libs#559]
You appear to be merging code to master with build errors relating to legacy addresses. Forcing code to merge upstream to avoid testing is extremely bad practice.

**Comment by eugene-babichenko** [comment]
What exact errors are you talking about? The CI have failing **lints** that do not affect the project build.

**Comment by hosekhoshtaghaza** [comment]
You can see the errors, there is a red x next to all of your recent merges showing they were forced due to failing checks. If the test doesn't matter, remove the test, if it is important it should be rectified locally before uploading publicly. You're uploading to master not a dev branch.
