### ISSUE TITLE
per-certificate fees

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/chain-libs#9]
Certificate might have different overhead on the chain, and thus might require more fees.

Introduce a certificate trait that allow to define extra fees depending on the certificate type and content, effectively `Certificate -> ExtraFee`

related to #427

**Comment by vincenthz** [comment]
replace the one-size-fits-all CertificateFees inside the LinearFees by something more flexible that allow
to set :

* global certificate base fee (could stay in LinearFees): catch all for all certificates that doesn't have any override
* stake pool registration fee (should be basically most expensive)
* stake pool delegation fee
* stake pool owner delegation fee (cheapest)

block0 (genesis) settings need update, and this need to apply the fee/cost correctly depending on the fragment in the ledger. and finally it need to be exposed in the server/rest client.

**Comment by eugene-babichenko** [comment]
Just to clarify:

- As I understand from the code, now **all** transactions just use one-size-fits-all `LinearFee` and there is no distinction between different types of transaction on how we calculate fees.
- Given that, we need to introduce fee calculation based on the type of a transaction.
- And then make special implementations for different certificate types.

Am I right?

**Comment by vincenthz** [comment]
it is mostly one-size-fits-all, however the fees has a parameter to calculate based on the actual type of certificate in `fees.rs` through:

```rust
fn calculate<'a>(&self, cert: Option<CertificateSlice<'a>>, inputs: u8, outputs: u8) -> Value
```

For now each certificate type goes through the `certificate` fee value in LinearFee:

```
pub struct LinearFee {
    pub constant: u64,
    pub coefficient: u64,
    pub certificate: u64,
}
```

we just need to add the `certificate_poolreg: u64` and `certificate_ownerstakedelegation: u64` ... fees and pattern match / associate each value properly
